spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/apportiondb
    username: apportion_user
    password: apportion_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
<<<<<<< HEAD
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
=======
  h2:
    console:
      enabled: true
      path: /h2-console
api:
  security:
    token:
      secret: ${JWT_SECRET:minha-chave-longa-e-segura-123412341234}
>>>>>>> 6448363d6c52ea1989dd64e8400e38aadc31b574
